<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-23T22:08:38 IST" name="Suite" finished-at="2024-10-23T22:10:16 IST" duration-ms="98023">
    <groups>
    </groups>
    <test started-at="2024-10-23T22:08:38 IST" name="Test" finished-at="2024-10-23T22:10:16 IST" duration-ms="98023">
      <class name="testCases.TC_01_AccouuntRegister">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC_01_AccouuntRegister@2bd08376]" started-at="2024-10-23T22:08:38 IST" name="setUp" finished-at="2024-10-23T22:08:50 IST" duration-ms="12216" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[EDGE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Register()[pri:0, instance:testCases.TC_01_AccouuntRegister@2bd08376]" started-at="2024-10-23T22:08:50 IST" name="Register" finished-at="2024-10-23T22:09:08 IST" duration-ms="17349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Register -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_01_AccouuntRegister@2bd08376]" started-at="2024-10-23T22:09:08 IST" name="tearDown" finished-at="2024-10-23T22:09:27 IST" duration-ms="19303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_01_AccouuntRegister -->
      <class name="testCases.TC_02_Login">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC_02_Login@b7c4869]" started-at="2024-10-23T22:09:27 IST" name="setUp" finished-at="2024-10-23T22:09:38 IST" duration-ms="10605" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[EDGE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="login()[pri:0, instance:testCases.TC_02_Login@b7c4869]" started-at="2024-10-23T22:09:38 IST" name="login" finished-at="2024-10-23T22:09:55 IST" duration-ms="16859" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account123] but found [My Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account123] but found [My Account]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.TC_02_Login.login(TC_02_Login.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_02_Login@b7c4869]" started-at="2024-10-23T22:09:55 IST" name="tearDown" finished-at="2024-10-23T22:10:16 IST" duration-ms="21098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_02_Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
